# Generated by Django 3.0.1 on 2020-01-08 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('url_id', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='itemphotos')),
                ('name', models.CharField(default='', max_length=200)),
                ('inventory', models.IntegerField(default=0)),
                ('price', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('ingridients', models.TextField(default='')),
                ('size', models.CharField(default='', max_length=200)),
                ('production', models.CharField(default='', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Categories')),
            ],
        ),
    ]
