# Generated by Django 3.0.1 on 2020-01-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200109_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='not_available',
            field=models.BooleanField(default=True),
        ),
    ]
