# Generated by Django 3.0.1 on 2020-01-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_not_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='url_id',
        ),
        migrations.AddField(
            model_name='categories',
            name='category_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='new_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='same_product_photo',
            field=models.ImageField(blank=True, upload_to='itemphotos'),
        ),
        migrations.AddField(
            model_name='item',
            name='same_product_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='url_item',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='not_available',
            field=models.BooleanField(default=False),
        ),
    ]
