# Generated by Django 3.0.1 on 2020-01-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200119_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='new_price',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
